Decode subprocess output
When export fails the output should be messaged to the user. This
however did not work on Python 3 because the result of p.communicate()
is a tuple of bytes and join() expects strings. This lead to the error:

    TypeError: sequence item 0: expected str instance, bytes found